# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "App Store Connectに署名済みビルドをアップロード"
  lane :upload do |options|
    key_id = options[:key_id]
    issuer_id = [:issuer_id]
    key_filepath = [:key_filepath]
    
    # 自動署名
    # automatic_code_signing(
    #   use_automatic_signing: true,
    #   team_id: Appfile.team_id
    # )
    # ビルド(ipa生成)
    # gym(
    #   scheme: "FastlaneApp",
    #   output_directory: "./build",
    #   output_name: "FastlaneApp.ipa",
    #   export_xcargs: "-allowProvisioningUpdates" # プロビジョニングプロファイルを自動的に更新
    # )
    # 認証(JWTの生成)
    # TODO: それぞれ用意する
    # https://arc.net/l/quote/mgbowczw
    api_key = app_store_connect_api_key(
      key_id: key_id,
      issuer_id: issuer_id,
      key_filepath: key_filepath
    )
    # App Store Connectにアップロード
    deliver(
      api_key: api_key,                       # 認証に使用するAPIキー
      force: true,                            # 以前のビルドを強制的に上書き
      # 提出情報に関する設定
      submission_information: {
        export_compliance_uses_encryption: false,    # 輸入コンプライアンス：暗号化を使用しない
        export_compliance_encryption_updated: false, # 暗号化の状況が更新されていない
        add_id_info_limits_tracking: false,          # ID情報によるトラッキング制限を追加しない
        add_id_info_uses_idfa: false,                # IDFAを使用しない
        add_id_info_serves_ads: false,               # 広告を提供しない
        add_id_info_tracks_action: false,            # アクションをトラッキングしない
        add_id_info_tracks_install: false            # インストールをトラッキングしない
      }
    )
  end
end
