# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "App Store Connectに署名済みビルドをアップロード"
  lane :upload do |options|
    key_id = options[:key_id]
    issuer_id = options[:issuer_id]
    key_filepath = options[:key_filepath]
    ipa_path = options[:ipa_path]
    
    # Bundle Versionのインクリメント
    increment_build_number(xcodeproj: "/Users/adamyoneda/development/fastlane_app/ios/Runner.xcodeproj")

    # 認証(JWTの生成)
    api_key = app_store_connect_api_key(
      key_id: key_id,
      issuer_id: issuer_id,
      key_filepath: key_filepath
    )

    # TestFlightの配布
    pilot(
      app_version: app_version,
      api_key: api_key,
      ipa: ipa_path
    )
  end
end
