# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "App Store Connectに署名済みビルドをアップロード"
  lane :upload do |options|
    work_space_path = options[:work_space_path]
    key_id = options[:key_id]
    issuer_id = options[:issuer_id]
    key_content = options[:key_content]
    ipa_path = options[:ipa_path]
    
    # Bundle Versionのインクリメント
    # increment_build_number(xcodeproj: work_space_path)

    # 認証(JWTの生成)
    api_key = app_store_connect_api_key(
      key_id: key_id,
      issuer_id: issuer_id,
      key_content: key_content,
      is_key_content_base64: true
    )

    # TestFlightの配布
    pilot(
      app_version: app_version,
      api_key: api_key,
      ipa: ipa_path
    )
  end
end
