name: Beta-distribute Dev app
on:
  push:
    tags:
      - v*
  workflow_dispatch:

env:
  export_options_plist: 'ios/export_options/ExportOptions.plist'
  fastlane_directory: 'ios/fastlane'
  ipa_file: '../../build/ios/ipa/fastlane_app.ipa'

jobs:
  beta-distribute-ios-app:
    name: Beta-distribute iOS app
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: Checks-out the repository
        uses: actions/checkout@v4
      
      - name: Install Gems
        run: bundle install
      
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.1'
      
      - name: Get Flutter dependencies
        run: flutter pub get
      
      - name: Decode App Store Connect API Key
        run: |
          mkdir -p ./private_keys
          echo "${{ secrets.APP_STORE_CONNECT_API_KEY }}" | base64 --decode > ./private_keys/AuthKey_${{ secrets.KEY_ID }}.p8
      
      - name: Build IPA
        run: |
          flutter build ios --release --no-codesign
          xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -sdk iphoneos -configuration Release archive -archivePath build/ios/Runner.xcarchive CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
          xcodebuild -exportArchive -archivePath build/ios/Runner.xcarchive -exportOptionsPlist ${{ env.export_options_plist }} -exportPath build/ios/ipa -allowProvisioningUpdates -authenticationKeyIssuerID ${{ secrets.ISSUER_ID }} -authenticationKeyID ${{ secrets.KEY_ID }} -authenticationKeyPath `pwd`/private_keys/AuthKey_${{ secrets.KEY_ID }}.p8
      
      - name: Distribute app with App Distribution
        run: bundle exec fastlane upload
        env:
          key_id: ${{ secrets.KEY_ID }}
          issuer_id: ${{ secrets.ISSUER_ID }}
          key_filepath: ${{ env.ipa_file }}
        working-directory: ${{ env.fastlane_directory }}
      
      - name: Remove App Store Connect API Key
        if: always()
        run: rm -f ./private_keys/AuthKey_${{ secrets.KEY_ID }}.p8
