name: Upload TestFlight
on:
  push:
    tags:
      - v*
  workflow_dispatch:

env:
  export_options_plist: 'ios/ipa/ExportOptions.plist'

jobs:
  beta-distribute-ios-app:
    name: Beta-distribute iOS app
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: Checks-out the repository
        uses: actions/checkout@v4
      
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.1'
      
      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Decode App Store Connect API Key
        run: |
          mkdir -p ./private_keys
          echo "${{ secrets.APP_STORE_CONNECT_API_KEY }}" > ./private_keys/AuthKey_${{ secrets.KEY_ID }}.p8
             
      - name: Build IPA
        run: |
          flutter build ios --release --no-codesign
          xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -sdk iphoneos -configuration Release archive -archivePath build/ios/Runner.xcarchive CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
          
      - name: Upload to App with ExportOptions.plist
        id: upload
        run: xcodebuild -exportArchive -archivePath build/ios/Runner.xcarchive -exportOptionsPlist ${{ env.export_options_plist }} -exportPath build/ios/ipa -allowProvisioningUpdates -authenticationKeyIssuerID ${{ secrets.ISSUER_ID }} -authenticationKeyID ${{ secrets.KEY_ID }} -authenticationKeyPath `pwd`/private_keys/AuthKey_${{ secrets.KEY_ID }}.p8
